project:
  version: @project.version@

app:
  java:
    version: @java.version@

spring:
  jpa:
#    properties:
#      hibernate:
#        format_sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    show-sql: true
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  thymeleaf:
    cache: false
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis

server:
  servlet:
    session:
      timeout: 10


