project:
  version: @project.version@

app:
  java:
    version: @java.version@

spring:
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  thymeleaf:
    cache: false
  redis:
    host: ${REDIS_URL}
    port: 6379
  session:
    store-type: redis

server:
  servlet:
    session:
      timeout: 10
  port: 5000

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

